baseurl: /react
name: React
description: The React is a real-time web application framework.
url: http://atmosphere.github.io/react/
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables
    - with_toc_data