baseurl: /wes
name: wes
description: The wes (Web Event Source) is an event-driven abstraction layer for various web application platforms that runs on the Java Virtual Machine
url: http://flowersinthesand.github.io/wes/
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables
    - with_toc_data
relative_permalinks: false
permalink: pretty