baseurl: /vibe
name: Vibe
description: Vibe, the modern web framework for writing real-time web applications.
url: http://atmosphere.github.io/vibe/
relative_permalinks: false
permalink: /blog/:title/
paginate: 5
paginate_path: "/blog/page:num/"
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables